const nodes = [
  [1, "Pozo 1", "#ff00ff"],
  [2, "Pozo 2", "#ff00ff"],
  [3, "Pozo 3", "#ff00ff"],
  [4, "Pozo 4", "#ff00ff"],
  [5, "Tanque Ppal", "#ff00ff"],
  [6, "A oficinas, trainig center, vigilancia", "#ff00ff"],
  [7, "API", "#ff00ff"],
  [8, "Torre de enfriamiento", "#ff00ff"],
  [9, "Calderas", "#ff00ff"],
  [10, "Sec.Arsenico", "#ff00ff"],
  [11, "Osmosis", "#ff00ff"],
  [12, "Primario", "#ff00ff"],
  [13, "Secundario", "#ff00ff"],
  [14, "Depositos", "#ff00ff"],
  [15, "Baños/Comedor", "#ff00ff"],
  [16, "Perdidas", "#ff00ff"],
  [17, "Agua en prodcuto", "#ff00ff"],
  [18, "Consumo humano", "#ff00ff"],
  [19, "PTEL", "#ff00ff"],
  [20, "Arroyo", "#ff00ff"],
  [21, "Desaireador", "#ff00ff"],
  [22, "Tanque de almacenamiento", "#ff00ff"],
  [23, "TK diario 16 m3", "#ff00ff"],
  [24, "TKs Calderas 2 (4 m3)", "#ff00ff"],
  [25, "Tanque Potable 20 m3", "#ff00ff"],
  [26, "Colector Industrial", "#ff00ff"],
  [27, "Colector cloacal", "#ff00ff"],
  [28, "Condensado", "#ff00ff"],
];
const linkTypes = [
  [1, "Vapor", "red"],
  [2, "Industrial", "cyan"],
  [3, "Potable", "green"],
  [4, "Drenaje", "yellow"],
];
const links = [
  [1, 5, 2, 39071.27, "m3/año"],
  [2, 5, 2, 14299.4, "m3/año"],
  [3, 5, 2, 31953.93, "m3/año"],
  [4, 6, 2, 31953.93, "m3/año"],
  [5, 7, 2, 1647.96, "m3/año"],
  [5, 8, 2, 22993.04, "m3/año"],
  [8, 9, 2, 2240.9, "m3/año"],
  [5, 10, 2, 5851.46, "m3/año"],
  [5, 11, 2, 36434.3, "m3/año"],
  [5, 12, 2, 718.39, "m3/año"],
  [5, 13, 2, 266.5, "m3/año"],
  [5, 14, 2, 1325, "m3/año"],
  [5, 15, 2, 0, "m3/año"],
  [12, 16, 1, 1918.62, "m3/año"],
  [12, 17, 2, 1493.34, "m3/año"],
  [19, 20, 3, 20075, "m3/año"],
  [27, 19, 4, 10658.55, "m3/año"],
  [25, 12, 3, 6647.43, "m3/año"],
  [25, 13, 3, 1589.5, "m3/año"],
  [25, 14, 3, 0, "m3/año"],
  [25, 15, 3, 10529.43, "m3/año"],
  [11, 25, 3, 21170.7, "m3/año"],
  [11, 20, 2, 10930.29, "m3/año"],
  [11, 24, 2, 10184.78, "m3/año"],
  [23, 21, 3, 10185, "m3/año"],
  [24, 23, 3, 0, "m3/año"],
  [28, 23, 3, 2098.4, "m3/año"],
  [10, 25, 2, 31355.5, "m3/año"],
  [21, 9, 3, 10185, "m3/año"],
  [9, 21, 1, 305, "m3/año"],
  [9, 16, 1, 10180, "m3/año"],
];

const data = {
  nodes: [
    { name: "Pozo 1", type: "well" },
    { name: "Pozo 2", type: "well" },
    { name: "Pozo 3", type: "well" },
    { name: "Pozo 4", type: "well" },
    { name: "Tanque Ppal", type: "tank" },
    { name: "A oficinas, trainig center, vigilancia", type: "coso" },
    { name: "API", type: "coso" },
    { name: "Torre de enfriamiento", type: "cooling_tower" },
    { name: "Calderas", type: "boiler" },
    { name: "Sec.Arsenico", type: "coso" },
    { name: "Osmosis", type: "coso" },
    { name: "Primario", type: "plant" },
    { name: "Secundario", type: "plant" },
    { name: "Depositos", type: "store" },
    { name: "Baños/Comedor", type: "bathroom" },
    { name: "Perdidas", type: "coso" },
    { name: "Agua en prodcuto", type: "coso" },
    { name: "Consumo humano", type: "coso" },
    { name: "PTEL", type: "coso" },
    { name: "Arroyo", type: "body of water" },
    { name: "Desaireador", type: "coso" },
    { name: "Tanque de almacenamiento", type: "tank" },
    { name: "TK diario 16 m3", type: "tank" },
    { name: "TKs Calderas 2 (4 m3)", type: "tank" },
    { name: "Tanque Potable 20 m3", type: "tank" },
    { name: "Colector Industrial", type: "collector" },
    { name: "Colector cloacal", type: "collector" },
    { name: "Condensado", type: "coso" },
  ],
  links: [
    {
      source: "Pozo 1",
      target: "Tanque Ppal",
      value: 39071.27,
      type: "industrial",
    },
    {
      source: "Pozo 2",
      target: "Tanque Ppal",
      value: 14299.4,
      type: "industrial",
    },
    {
      source: "Pozo 3",
      target: "Tanque Ppal",
      value: 31953.93,
      type: "industrial",
    },
    {
      source: "Pozo 4",
      target: "A oficinas, trainig center, vigilancia",
      value: 31953.93,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "API",
      value: 1647.96,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Torre de enfriamiento",
      value: 22993.04,
      type: "industrial",
    },
    {
      source: "Torre de enfriamiento",
      target: "Calderas",
      value: 2240.9,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Sec.Arsenico",
      value: 5851.46,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Osmosis",
      value: 36434.3,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Primario",
      value: 718.39,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Secundario",
      value: 266.5,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Depositos",
      value: 1325,
      type: "industrial",
    },
    {
      source: "Tanque Ppal",
      target: "Baños/Comedor",
      value: 0,
      type: "industrial",
    },
    {
      source: "Primario",
      target: "Perdidas",
      value: 1918.62,
      type: "steam",
    },
    {
      source: "Primario",
      target: "Agua en prodcuto",
      value: 1493.34,
      type: "industrial",
    },
    {
      source: "PTEL",
      target: "Arroyo",
      value: 20075,
      type: "potable",
    },
    {
      source: "Colector cloacal",
      target: "PTEL",
      value: 10658.55,
      type: "drain",
    },
    {
      source: "Tanque Potable 20 m3",
      target: "Primario",
      value: 6647.43,
      type: "potable",
    },
    {
      source: "Tanque Potable 20 m3",
      target: "Secundario",
      value: 1589.5,
      type: "potable",
    },
    {
      source: "Tanque Potable 20 m3",
      target: "Depositos",
      value: 0,
      type: "potable",
    },
    {
      source: "Tanque Potable 20 m3",
      target: "Baños/Comedor",
      value: 10529.43,
      type: "potable",
    },
    {
      source: "Osmosis",
      target: "Tanque Potable 20 m3",
      value: 21170.7,
      type: "potable",
    },
    {
      source: "Osmosis",
      target: "Arroyo",
      value: 10930.29,
      type: "industrial",
    },
    {
      source: "Osmosis",
      target: "TKs Calderas 2 (4 m3)",
      value: 10184.78,
      type: "industrial",
    },
    {
      source: "TK diario 16 m3",
      target: "Desaireador",
      value: 10185,
      type: "potable",
    },
    {
      source: "TKs Calderas 2 (4 m3)",
      target: "TK diario 16 m3",
      value: 0,
      type: "potable",
    },
    {
      source: "Condensado",
      target: "TK diario 16 m3",
      value: 2098.4,
      type: "potable",
    },
    {
      source: "Sec.Arsenico",
      target: "Tanque Potable 20 m3",
      value: 31355.5,
      type: "industrial",
    },
    {
      source: "Desaireador",
      target: "Calderas",
      value: 10185,
      type: "potable",
    },
    {
      source: "Calderas",
      target: "Desaireador",
      value: 305,
      type: "steam",
    },
    {
      source: "Calderas",
      target: "Perdidas",
      value: 10180,
      type: "steam",
    },
  ],
};
